collect linting errors but don't exit

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,15 +18,15 @@ jobs:
           command: |
             npm run lint
             LINT_EXIT_CODE=$?
-            if [ $lint_exit_code -ne 0 ]; then
-              continue
+            if [ $LINT_EXIT_CODE -ne 0 ]; then
               echo "Linting failed with exit code: $LINT_EXIT_CODE"
+              exit 1  # Exit the script with a non-zero status code to indicate failure
             fi
       - run:
           command: |
             set -e
             mkdir /tmp/test_reports
-            cat $LINT_EXIT_CODE > ~/tmp/test_reports/lint_error.txt
+            cat $LINT_EXIT_CODE > /tmp/test_reports/lint_error.txt
           when: always
       - store_test_results:
           path: /tmp/test_reports
